# 6. Import Libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

%matplotlib inline
sns.set_theme(style="whitegrid")

# 7. Load Data
df = pd.read_csv("hospital_data.csv")
df.head()

# Part 1
# 8. Dataset Understanding
# Q1. How many rows and columns are present?
df.shape

# Q2. Display first 10 records.
df.head(10)

# Q3. Display last 10 records.
df.tail(10)

# Q4. Display all column names.
df.columns

# Q5. Check data types.
df.dtypes

# Q6. Get complete dataset information.
df.info()

# Q7. Generate statistical summary.
df.describe()

# 9. Data Quality
# Q8. Find missing values.
df.isnull().sum()

# Q9. Find duplicate rows.
df.duplicated().sum()

# Q10. Remove duplicates.
df = df.drop_duplicates()

# Q11. Check unique values in Department.
df["Department"].unique()

# Q12. Check unique values in Disease.
df["Disease"].unique()

# 10. Date Processing
# Q13. Convert date columns.
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])

# Q14. Create Year, Month and Month_Name.
df["Year"] = df["Admission_Date"].dt.year
df["Month"] = df["Admission_Date"].dt.month
df["Month_Name"] = df["Admission_Date"].dt.month_name()

# Q15. Create Day of Week.
df["Day_Name"] = df["Admission_Date"].dt.day_name()

# 11. Feature Engineering
# Q16. Create age groups.
bins = [0, 18, 35, 50, 65, 100]
labels = ["Child", "Young Adult", "Adult", "Senior", "Elderly"]
df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

# Q17. Create a high-bill flag.
average_bill = df["Bill_Amount"].mean()
df["High_Bill"] = np.where(df["Bill_Amount"] > average_bill, "Yes", "No")

# Part 2
# 12. Basic KPIs
# Q18. Total number of patients.
total_patients = df["Patient_ID"].nunique()
print(total_patients)

# Q19. Total revenue.
total_revenue = df["Bill_Amount"].sum()
print(round(total_revenue, 2))

# Q20. Average hospital bill.
average_bill = df["Bill_Amount"].mean()
print(round(average_bill, 2))

# Q21. Minimum bill.
df["Bill_Amount"].min()

# Q22. Maximum bill.
df["Bill_Amount"].max()

# Q23. Average length of stay.
df["Length_of_Stay"].mean()

# Q24. Average satisfaction.
df["Satisfaction"].mean()

# 13. Patient Demographics
# Q25. Number of patients by gender.
df["Gender"].value_counts()

# Q26. Number of patients by city.
df["City"].value_counts()

# Q27. Number of patients by age group.
df["Age_Group"].value_counts()

# Q28. Which age group has the most patients?
df["Age_Group"].value_counts().idxmax()

# 14. Department Analysis
# Q29. Number of patients by department.
department_patients = df["Department"].value_counts()
department_patients

# Q30. Which department has the highest patient count?
department_patients.idxmax()

# Q31. Total revenue by department.
department_revenue = (
    df.groupby("Department")["Bill_Amount"].sum().sort_values(ascending=False)
)
department_revenue

# Q32. Which department generates the highest revenue?
department_revenue.idxmax()

# Q33. Average bill by department.
df.groupby("Department")["Bill_Amount"].mean().sort_values(ascending=False)

# Q34. Average stay by department.
df.groupby("Department")["Length_of_Stay"].mean().sort_values(ascending=False)

# Q35. Average satisfaction by department.
df.groupby("Department")["Satisfaction"].mean().sort_values(ascending=False)

# 15. Disease Analysis
# Q36. Most common diseases.
disease_count = df["Disease"].value_counts()
disease_count

# Q37. Top 5 diseases.
disease_count.head(5)

# Q38. Revenue by disease.
disease_revenue = (
    df.groupby("Disease")["Bill_Amount"].sum().sort_values(ascending=False)
)
disease_revenue

# Q39. Average bill by disease.
df.groupby("Disease")["Bill_Amount"].mean().sort_values(ascending=False)

# Q40. Disease with highest revenue.
disease_revenue.idxmax()

# 16. Doctor Analysis
# Q41. Number of patients handled by each doctor.
doctor_count = df["Doctor"].value_counts()
doctor_count

# Q42. Top 5 doctors by patient count.
doctor_count.head(5)

# Q43. Average satisfaction by doctor.
df.groupby("Doctor")["Satisfaction"].mean().sort_values(ascending=False)

# Q44. Revenue generated by each doctor.
doctor_revenue = (
    df.groupby("Doctor")["Bill_Amount"].sum().sort_values(ascending=False)
)
doctor_revenue

# 17. Monthly Analysis
# Q45. Monthly admissions.
monthly_admissions = df.groupby("Month")["Patient_ID"].count()
monthly_admissions

# Q46. Monthly revenue.
monthly_revenue = df.groupby("Month")["Bill_Amount"].sum()
monthly_revenue

# Q47. Month with highest admissions.
monthly_admissions.idxmax()

# Q48. Month with highest revenue.
monthly_revenue.idxmax()

# 18. Length of Stay
# Q49. Maximum hospital stay.
df["Length_of_Stay"].max()

# Q50. Patients staying more than 10 days.
long_stay = df[df["Length_of_Stay"] > 10]
long_stay

# Q51. Does length of stay affect bill amount?
df[["Length_of_Stay", "Bill_Amount"]].corr()

# 19. Insurance Analysis
# Q52. Number of patients by insurance type.
df["Insurance_Type"].value_counts()

# Q53. Average bill by insurance type.
df.groupby("Insurance_Type")["Bill_Amount"].mean()

# Q54. Revenue by insurance type.
insurance_revenue = (
    df.groupby("Insurance_Type")["Bill_Amount"]
    .sum()
    .sort_values(ascending=False)
)
insurance_revenue

# Q55. Which insurance type generates the most revenue?
insurance_revenue.idxmax()

# 20. Payment Analysis
# Q56. Most common payment mode.
df["Payment_Mode"].value_counts()

# Q57. Revenue by payment mode.
df.groupby("Payment_Mode")["Bill_Amount"].sum().sort_values(ascending=False)

# 21. Readmission Analysis
# Q58. Count readmitted patients.
df["Readmitted"].value_counts()

# Q59. Calculate readmission rate.
readmission_rate = df["Readmitted"].eq("Yes").mean() * 100
print(round(readmission_rate, 2), "%")

# Q60. Readmission by department.
pd.crosstab(df["Department"], df["Readmitted"], normalize="index") * 100

# Q61. Which department has the highest readmission rate?
readmission_table = (
    pd.crosstab(df["Department"], df["Readmitted"], normalize="index") * 100
)
readmission_table["Yes"].idxmax()

# 22. Satisfaction Analysis
# Q62. Average satisfaction by department.
satisfaction_department = (
    df.groupby("Department")["Satisfaction"]
    .mean()
    .sort_values(ascending=False)
)
satisfaction_department

# Q63. Departments with satisfaction below 4.
satisfaction_department[satisfaction_department < 4]

# Q64. Average satisfaction by gender.
df.groupby("Gender")["Satisfaction"].mean()

# 23. Advanced GroupBy
# Q65. Create a department KPI table.
department_kpi = (
    df.groupby("Department")
    .agg(
        Patients=("Patient_ID", "count"),
        Revenue=("Bill_Amount", "sum"),
        Average_Bill=("Bill_Amount", "mean"),
        Average_Stay=("Length_of_Stay", "mean"),
        Satisfaction=("Satisfaction", "mean"),
    )
    .sort_values("Revenue", ascending=False)
)
department_kpi

# 24. Crosstab Analysis
# Q66. Department vs gender.
pd.crosstab(df["Department"], df["Gender"])

# Q67. Disease vs gender.
pd.crosstab(df["Disease"], df["Gender"])

# Q68. Department vs insurance type.
pd.crosstab(df["Department"], df["Insurance_Type"])

# 25. Pivot Table
# Q69. Department vs insurance revenue.
pivot = pd.pivot_table(
    df,
    values="Bill_Amount",
    index="Department",
    columns="Insurance_Type",
    aggfunc="sum",
)
pivot

# 26. Top-Billing Patients
# Q70. Top 10 highest-billing patients.
top10 = df.nlargest(10, "Bill_Amount")
top10[
    [
        "Patient_Code",
        "Department",
        "Disease",
        "Length_of_Stay",
        "Bill_Amount",
    ]
]

# 27. Filtering Questions
# Q71. Patients with bill above average.
df[df["Bill_Amount"] > df["Bill_Amount"].mean()]

# Q72. Patients with satisfaction below 3.
df[df["Satisfaction"] < 3]

# Q73. Patients staying more than 7 days and bill above ₹75,000.
df[(df["Length_of_Stay"] > 7) & (df["Bill_Amount"] > 75000)]

# Q74. Senior patients with readmission.
df[(df["Age"] >= 65) & (df["Readmitted"] == "Yes")]

# Part 3
# 28. MATPLOTLIB CHARTS
# Chart 1 - Patients by Department
department_count = df["Department"].value_counts().sort_values(ascending=True)
plt.figure(figsize=(10, 6))
plt.barh(department_count.index, department_count.values) #barh=ka matlab hai Horizontal Bar Chart.
plt.title("Number of Patients by Department")
plt.xlabel("Number of Patients")
plt.ylabel("Department")
plt.tight_layout() #Graph ke margins aur labels ke beech ki spacing auto-adjust karta hai
plt.show()

# Chart 2 - Monthly Admissions
plt.figure(figsize=(10, 5))
plt.plot(
    monthly_admissions.index, monthly_admissions.values, marker="o"
)
plt.title("Monthly Patient Admissions")
plt.xlabel("Month")
plt.ylabel("Number of Patients")
plt.xticks(range(1, 13))
plt.tight_layout()
plt.show()

# Chart 3 - Monthly Revenue
plt.figure(figsize=(10, 5))
plt.plot(monthly_revenue.index, monthly_revenue.values, marker="o")
plt.title("Monthly Hospital Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(range(1, 13))
plt.tight_layout()
plt.show()

# Chart 4 - Gender Distribution
gender_count = df["Gender"].value_counts()
plt.figure(figsize=(7, 7))
plt.pie(
    gender_count.values,
    labels=gender_count.index,
    autopct="%1.1f%%",
    startangle=90,
)
plt.title("Patient Gender Distribution")
plt.show()

# Chart 5 - Age Distribution
plt.figure(figsize=(10, 5))
plt.hist(df["Age"], bins=15, edgecolor="black")
plt.title("Patient Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Patients")
plt.show()

# Chart 6 - Revenue by Department
department_revenue = (
    df.groupby("Department")["Bill_Amount"].sum().sort_values(ascending=True)
)
plt.figure(figsize=(10, 6))
plt.barh(department_revenue.index, department_revenue.values)
plt.title("Revenue by Department")
plt.xlabel("Revenue")
plt.ylabel("Department")
plt.tight_layout()
plt.show()

# 29. SEABORN CHARTS
# Chart 7 - Disease Distribution
plt.figure(figsize=(10, 6))
order = df["Disease"].value_counts().index
sns.countplot(data=df, y="Disease", order=order)
plt.title("Disease Distribution")
plt.tight_layout()
plt.show()

# Chart 8 - Bill Distribution
plt.figure(figsize=(10, 5))
sns.histplot(data=df, x="Bill_Amount", bins=30, kde=True)
plt.title("Hospital Bill Distribution")
plt.xlabel("Bill Amount")
plt.ylabel("Number of Patients")
plt.show()

# Chart 9 - Bill by Department
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="Department", y="Bill_Amount")
plt.title("Hospital Bill Distribution by Department")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Chart 10 - Length of Stay vs Bill
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df, x="Length_of_Stay", y="Bill_Amount", hue="Department"
)
plt.title("Length of Stay vs Hospital Bill")
plt.xlabel("Length of Stay")
plt.ylabel("Bill Amount")
plt.tight_layout()
plt.show()

# Chart 11 - Satisfaction by Department
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="Department", y="Satisfaction")
plt.title("Patient Satisfaction by Department")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Chart 12 - Correlation Heatmap
numeric_columns = ["Age", "Length_of_Stay", "Bill_Amount", "Satisfaction"]
corr = df[numeric_columns].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Hospital Data Correlation Heatmap")
plt.tight_layout()
plt.show()

# Part 4
# Challenge 8 - Solution
pd.crosstab(df["Disease"], df["Gender"])

# Challenge 9 - Solution
df.groupby("Department")["Satisfaction"].mean().idxmax()

# Challenge 10 - Solution
df.groupby("Month")["Bill_Amount"].sum().idxmax()

# Part 5
# 31. Final KPI Report
total_patients = df["Patient_ID"].nunique()
total_revenue = df["Bill_Amount"].sum()
average_bill = df["Bill_Amount"].mean()
average_stay = df["Length_of_Stay"].mean()
average_satisfaction = df["Satisfaction"].mean()
readmission_rate = df["Readmitted"].eq("Yes").mean() * 100
top_department = df["Department"].value_counts().idxmax()
top_disease = df["Disease"].value_counts().idxmax()
top_revenue_department = df.groupby("Department")["Bill_Amount"].sum().idxmax()

print("=" * 50)
print("HOSPITAL MANAGEMENT KPI REPORT")
print("=" * 50)
print("Total Patients:", total_patients)
print("Total Revenue:", round(total_revenue, 2))
print("Average Bill:", round(average_bill, 2))
print("Average Stay:", round(average_stay, 2))
print("Average Satisfaction:", round(average_satisfaction, 2))
print("Readmission Rate:", round(readmission_rate, 2), "%")
print("Highest Patient Volume:", top_department)
print("Most Common Disease:", top_disease)
print("Highest Revenue Department:", top_revenue_department)
print("=" * 50)